### ISSUE TITLE
[Feature Request]: add support for "raised"

### ISSUE THREAD

**Issue by Texbio** [Cheos137/ArmorpointsPlusplus#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when using this with the mod "raised" the hearts, hungerbar, and armor bar get lowered

### Version

3.0.x for Minecraft Fabric 1.19

### Version

armorpointspp-fabric-1.19-3.0.5

### To Reproduce

install fabric
install this mod
install raised

### Expexted Behavior

no lowering of hearts, hunger bar, and armor bar

### Screenshots

![armorpointspp raised](https://user-images.githubusercontent.com/36513888/194331605-344c035f-ca01-4fbd-a234-634cf0f493c7.png)

**Comment by Cheos137** [comment]
Due to the (nonexistent) way of how fabric handles mod compatibility (which shows especially for hud altering mods), stuff like that is expected to happen. So i won't consider this a bug in particular... but an incompatibility.
I can add support for raised though.. but won't give an ETA for it, at all.
