### ISSUE TITLE
[Feature Request]: add option to render multiple absorption bars over health bar.

### ISSUE THREAD

**Issue by murao-kun** [Cheos137/ArmorpointsPlusplus#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Recently I switched from this mod https://www.curseforge.com/minecraft/mc-mods/health-overlay to using that one.
This one is much more better. But I miss one feature still.
I need ability to stack absorption bar render over my health bar. 

### Solution

Like that. 
![image](https://user-images.githubusercontent.com/110398598/199251935-60472b55-531b-437a-bede-b2751aba30c4.png)
I also like that you can edit texture sheet instead of tinting with hex color. Will be also useful for cases when effect is reaching 20 health points.

**Comment by Cheos137** [comment]
Won't add this for v3.1.0 but in a later update

**Comment by murao-kun** [comment]
What if I will change it to simply adding absorption health render as only feature request for now? I see mod is not updating often. And I am making modpack that I want to release sometime in winter. It will be pointless for me to use that mod instead of mentioned the one above.
But I understand that this is complicated request. So I might simplify it to just that, to make at least to still get it in 3.1.0?

**Comment by Cheos137** [comment]
I'm not even sure whether i'll be able to get v3.1.0 still out this year because i'm very low on free time in which i have the energy to work on any of my active coding projects at the moment.

But okay - cuz you asked nicely i'll do it for v3.1.0... i'll try to get it at least into an alpha version as soon as i can... maybe even publish a beta (though the latter one is pretty unlikely... especially because alpha is pretty stable anyways)

**Comment by murao-kun** [comment]
Thank you! Don't rush, I am not planing to release my pack anytime soon too (probably 3 more months of work, since it is having a lot of configuration and own coding in it). So take you time and thank you a lot! I really appreciate that. :)
