### ISSUE TITLE
[Bug]: 1.16.5 Duplicated F3 debug info when armorpoint++ is installed(only for mods)

### ISSUE THREAD

**Issue by quentin452** [Cheos137/ArmorpointsPlusplus#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Duplicata F3 DEBUG INFO when botania + armorpoint++ is installed or botania + armorpoint++ is installed

**mods list**

* armorpointspp-forge-1.16.5-3.0.9
* Botania-1.16.5-420.3
* curios-forge-1.16.5-4.0.8.2
* Patchouli-1.16.4-53.3

### Version

3.0.x for Minecraft Forge 1.16.5

### Version

forge-1.16.5-3.0.9

### To Reproduce

1. open a world
2. use ALT + F3 hotkey
3. watch the duplicata

### Additional Context

Need to install botania or create + armorpoint++ to make this bug.

### Screenshots

armorpoint++ is enabled : 

![image](https://user-images.githubusercontent.com/42176772/216729354-52226aa4-4e8e-4221-a45d-cf55b3161d27.png)

armorpoint++ is disabled : 

![image](https://user-images.githubusercontent.com/42176772/216729563-ad736c45-e555-4eca-9ed3-3b7023f09a92.png)

### Relevant Log / Crash-Report Output

```shell
no log
```

**Comment by Cheos137** [comment]
Hi there, while i fully acknowledge this being an issue (thanks for reporting it), i will not fix this for the reasons outlined as follows:
* This issue is deep rooted within the rather complex 1.16.5 internals of ap++ (which makes it hard to debug and fix) - in addition, a fix could potentially break something more important
* This seems to be _very_ specific - and only affects a few lines of text (which aren't really relevant to begin with) - especially as ap++ doesn't modify the F3-Screen on it's own (making it a result of some other mod not functioning properly with ap++'s internals)
* It's a small issue - not worth the vast amount of time that would be needed to locate and fix the underlying issue
* 1.16.5 as a minecraft version is losing it's relevance to modding by the second - and small issues like this won't affect the overall player experience
* I'm very low on free time - and want to focus on what really needs to be fixed

So, i hope i didn't destroy your day by marking this as `wontfix` for these reasons ^^
If anyone wants to make a PR fixing this - all contributions are welcome

**Comment by quentin452** [comment]
ok
