### ISSUE TITLE
[Bug]: [1.19.2] Health number display being rendered on the top of the screen

### ISSUE THREAD

**Issue by ffuentesm** [Cheos137/ArmorpointsPlusplus#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

The health number is displayed on top of the screen, not next to the hearts 

### Version

Other (this list is not up to date - again...)

### Version

ArmorPoints++ v3.0.9 [FORGE 1.19]

### Expexted Behavior

Red Numbers should be next to the hearts

### Additional Context

Mod list: https://crashy.net/8ae0dcdb-978e-4cd6-b94f-19d2c86310c3

### Screenshots

![image](https://user-images.githubusercontent.com/44974827/219942381-7e36cf92-43f7-4a8a-bba4-b99baf87aeef.png)

**Comment by Cheos137** [comment]
happens if some other mods overrides heart rendering (like mantle does, for example) by cancelling forge's heart component render event - not a bug of armorpoints++ (if you're using mantle, you need to configure mantle to not replace the health bar, otherwise you might have to remove the mod replacing the health bar)

**Comment by Cheos137** [comment]
you could also manually set the text position in armorpoints++'s config if you want to keep the overridden heart rendering - there is no option to determine the position automatically, as armorpoints++'s rendering code is not called if cancelled.
